_config.yml:
theme: minima
title: Alias Societas
author: Charly García
email: jcgl@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Blog de proyecto acerca de la construcción del discurso, dinámica y acción sociocultural.
# social links
twitter_username: garcialopezjc # DO NOT include the @ character, or else the build will fail!
github_username:  garcialopezjc # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
